clone:
  depth: full

definitions:
  caches:
    pnpmwebapp: $BITBUCKET_CLONE_DIR/.pnpm-store
    pnpmcore: $BITBUCKET_CLONE_DIR/.pnpm-store
    pnpmapiclient: $BITBUCKET_CLONE_DIR/.pnpm-store
    pnpmgraphqlapi: $BITBUCKET_CLONE_DIR/.pnpm-store

  scripts:
    initializeStep: &initializeStep cp .env.shared .env
      && corepack enable
      && corepack prepare pnpm@8.6.1 --activate
      && export PNPM_HOME="/root/.local/share/pnpm"
      && export PATH="$PNPM_HOME:$PATH"

    installWebappDeps: &installWebappDeps pnpm install
      --include-workspace-root
      --frozen-lockfile
      --filter=app...

  steps:
    - step: &webappTest
        name: 'webapp: Lint & test'
        image: atlassian/default-image:4
        script:
          - *initializeStep
          - *installWebappDeps
          - pnpm nx run app:lint
          - pnpm nx run app:type-check
          - pnpm nx run app:test --watchAll=false --maxWorkers=20% --coverage
        caches:
          - pnpmwebapp
    - step: &webappBuild
        name: 'webapp: Build'
        image: atlassian/default-image:4
        script:
          - *initializeStep
          - *installWebappDeps
          - pnpm nx run app:build
        caches:
          - pnpmwebapp
    - step: &coreTest
        name: 'core: Lint & test'
        image: atlassian/default-image:4
        script:
          - *initializeStep
          - pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=core...
          - pnpm nx run core:lint
          - pnpm nx run core:type-check
          - pnpm nx run core:test --watchAll=false --maxWorkers=20% --coverage
        caches:
          - pnpmcore
    - step: &apiClientTest
        name: 'api-client: Lint & test'
        image: atlassian/default-image:4
        script:
          - *initializeStep
          - pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=api-client...
          - pnpm nx run api-client:lint
          - pnpm nx run api-client:type-check
          - pnpm nx run api-client:test --watchAll=false --maxWorkers=20% --coverage
        caches:
          - pnpmapiclient
    - step: &graphqlApiTest
        name: 'graphql-api: Lint & test'
        image: atlassian/default-image:4
        script:
          - *initializeStep
          - pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=graphql-api...
          - pnpm nx run graphql-api:lint
          - pnpm nx run graphql-api:type-check
          - pnpm nx run graphql-api:test --watchAll=false --maxWorkers=20% --coverage
        caches:
          - pnpmgraphqlapi

pipelines:
  default:
    - parallel:
        - step: *webappTest
        - step: *webappBuild
        - step: *coreTest
        - step: *apiClientTest
        - step: *graphqlApiTest

  branches:
    master:
      - parallel:
        - step: *webappTest
        - step: *webappBuild
        - step: *coreTest
        - step: *apiClientTest
        - step: *graphqlApiTest