version: "3.4"

services:
  db:
    image: postgres:13.7
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
