version: "3.4"

volumes:
  web_backend_db_data:
    name: "${PROJECT_NAME}-web-backend-db-data"
    external: true

services:
  db:
    volumes:
      - web_backend_db_data:/var/lib/postgresql/data

  mailcatcher:
    platform: linux/amd64
    build: ./packages/internal/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always