name: "\U0001F41E Bug report"
description: Report an issue with ALPack
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described. If applicable, add screenshots to help explain your problem.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages  --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Please try not to insert an image but copy paste the log text.

        Provide the error log here in the format below.

        ````
        <details>
        <summary>Click to expand!</summary>

        ```shell
        // paste the log text here
        ```
        </details>
        ````
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/apptension/alpack/blob/master/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/apptension/alpack/blob/master/CONTRIBUTING.md).
          required: true
#        - label: Read the [docs](https://docs.alpack.apptoku.com/).
#          required: true
        - label: Check that there isn't [already an issue](https://github.com/apptension/alpack/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/apptension/alpack/discussions) or join our [Discord Chat Server](https://discord.apptension.com).
          required: true