blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.apptension.com
    about: Ask questions and discuss with other ALPack users.
  - name: Questions & Discussions
    url: https://github.com/apptension/alpack/discussions
    about: Use GitHub discussions for message-board style questions and discussions.