name: "\U0001F4DA Documentation"
description: Suggest a change or new page to be added to the documentation of the ALPack
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this issue!
  - type: checkboxes
    id: documentation_is
    attributes:
      label: Documentation is
      options:
        - label: Missing
        - label: Outdated
        - label: Confusing
        - label: Not sure?
  - type: textarea
    id: description
    attributes:
      label: Explain in detail
      description: A clear and concise description of your suggestion. If you intend to submit a PR for this issue, tell us in the description.
      placeholder: The description of ... page is not clear. I thought it meant ... but it wasn't.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion for Changes
    validations:
      required: true