name: "internal-tools"

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - shell: bash
        run: pnpm install
          --include-workspace-root
          --frozen-lockfile
          --filter=internal-tools...

      - name: Lint
        shell: bash
        run: pnpm nx run internal-tools:lint
